#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re
import json

def parse_oxford_words():
    """Parse Oxford 3000 words from text file and create structured database"""
    
    # Read the text file
    with open('/home/ubuntu/oxford_words.txt', 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Dictionary to store words by level
    words_by_level = {
        'A1': [],
        'A2': [],
        'B1': [],
        'B2': []
    }
    
    # Basic translations for common words (simplified for demo)
    basic_translations = {
        # A1 level common words
        'a': 'один, одна, одно',
        'an': 'один, одна, одно',
        'about': 'о, около',
        'above': 'над, выше',
        'across': 'через',
        'action': 'действие',
        'activity': 'деятельность',
        'actor': 'актер',
        'actress': 'актриса',
        'add': 'добавлять',
        'address': 'адрес',
        'adult': 'взрослый',
        'advice': 'совет',
        'afraid': 'боящийся',
        'after': 'после',
        'afternoon': 'день',
        'again': 'снова',
        'age': 'возраст',
        'ago': 'назад',
        'agree': 'соглашаться',
        'air': 'воздух',
        'airport': 'аэропорт',
        'all': 'все',
        'also': 'также',
        'always': 'всегда',
        'amazing': 'удивительный',
        'and': 'и',
        'angry': 'злой',
        'animal': 'животное',
        'another': 'другой',
        'answer': 'ответ',
        'any': 'любой',
        'anyone': 'кто-нибудь',
        'anything': 'что-нибудь',
        'apartment': 'квартира',
        'apple': 'яблоко',
        'april': 'апрель',
        'area': 'область',
        'arm': 'рука',
        'around': 'вокруг',
        'arrive': 'прибывать',
        'art': 'искусство',
        'article': 'статья',
        'artist': 'художник',
        'as': 'как',
        'ask': 'спрашивать',
        'at': 'в, на',
        'august': 'август',
        'aunt': 'тетя',
        'autumn': 'осень',
        'away': 'прочь',
        'baby': 'ребенок',
        'back': 'назад',
        'bad': 'плохой',
        'bag': 'сумка',
        'ball': 'мяч',
        'banana': 'банан',
        'band': 'группа',
        'bank': 'банк',
        'bath': 'ванна',
        'bathroom': 'ванная',
        'be': 'быть',
        'beach': 'пляж',
        'beautiful': 'красивый',
        'because': 'потому что',
        'become': 'становиться',
        'bed': 'кровать',
        'bedroom': 'спальня',
        'beer': 'пиво',
        'before': 'до',
        'begin': 'начинать',
        'beginning': 'начало',
        'behind': 'за',
        'believe': 'верить',
        'below': 'ниже',
        'best': 'лучший',
        'better': 'лучше',
        'between': 'между',
        'bicycle': 'велосипед',
        'big': 'большой',
        'bike': 'велосипед',
        'bill': 'счет',
        'bird': 'птица',
        'birthday': 'день рождения',
        'black': 'черный',
        'blog': 'блог',
        'blonde': 'блондин',
        'blue': 'синий',
        'boat': 'лодка',
        'body': 'тело',
        'book': 'книга',
        'boot': 'ботинок',
        'bored': 'скучающий',
        'boring': 'скучный',
        'born': 'рожденный',
        'both': 'оба',
        'bottle': 'бутылка',
        'box': 'коробка',
        'boy': 'мальчик',
        'boyfriend': 'парень',
        'bread': 'хлеб',
        'break': 'ломать',
        'breakfast': 'завтрак',
        'bring': 'приносить',
        'brother': 'брат',
        'brown': 'коричневый',
        'build': 'строить',
        'building': 'здание',
        'bus': 'автобус',
        'business': 'бизнес',
        'busy': 'занятый',
        'but': 'но',
        'butter': 'масло',
        'buy': 'покупать',
        'by': 'у, около',
        'bye': 'пока',
        'cafe': 'кафе',
        'cake': 'торт',
        'call': 'звонить',
        'camera': 'камера',
        'can': 'мочь',
        'cannot': 'не мочь',
        'capital': 'столица',
        'car': 'машина',
        'card': 'карта',
        'career': 'карьера',
        'carrot': 'морковь',
        'carry': 'нести',
        'cat': 'кот',
        'cd': 'диск',
        'cent': 'цент',
        'centre': 'центр',
        'century': 'век',
        'chair': 'стул',
        'change': 'изменять',
        'chart': 'график',
        'cheap': 'дешевый',
        'check': 'проверять',
        'cheese': 'сыр',
        'chicken': 'курица',
        'child': 'ребенок',
        'chocolate': 'шоколад',
        'choose': 'выбирать',
        'cinema': 'кинотеатр',
        'city': 'город',
        'class': 'класс',
        'classroom': 'классная комната',
        'clean': 'чистый',
        'climb': 'лазить',
        'clock': 'часы',
        'close': 'закрывать',
        'clothes': 'одежда',
        'club': 'клуб',
        'coat': 'пальто',
        'coffee': 'кофе',
        'cold': 'холодный',
        'college': 'колледж',
        'colour': 'цвет',
        'come': 'приходить',
        'common': 'общий',
        'company': 'компания',
        'compare': 'сравнивать',
        'complete': 'полный',
        'computer': 'компьютер',
        'concert': 'концерт',
        'conversation': 'разговор',
        'cook': 'готовить',
        'cooking': 'готовка',
        'cool': 'прохладный',
        'correct': 'правильный',
        'cost': 'стоить',
        'could': 'мог бы',
        'country': 'страна',
        'course': 'курс',
        'cousin': 'двоюродный брат',
        'cow': 'корова',
        'cream': 'крем',
        'create': 'создавать',
        'culture': 'культура',
        'cup': 'чашка',
        'customer': 'клиент',
        'cut': 'резать',
        'dad': 'папа',
        'dance': 'танцевать',
        'dancer': 'танцор',
        'dancing': 'танцы',
        'dangerous': 'опасный',
        'dark': 'темный',
        'date': 'дата',
        'daughter': 'дочь',
        'day': 'день',
        'dear': 'дорогой',
        'december': 'декабрь',
        'decide': 'решать',
        'delicious': 'вкусный',
        'describe': 'описывать',
        'description': 'описание',
        'design': 'дизайн',
        'desk': 'стол',
        'detail': 'деталь',
        'dialogue': 'диалог',
        'dictionary': 'словарь',
        'die': 'умирать',
        'diet': 'диета',
        'difference': 'разница',
        'different': 'разный',
        'difficult': 'трудный',
        'dinner': 'ужин',
        'dirty': 'грязный',
        'discuss': 'обсуждать',
        'dish': 'блюдо',
        'do': 'делать',
        'doctor': 'врач',
        'dog': 'собака',
        'dollar': 'доллар',
        'door': 'дверь',
        'down': 'вниз',
        'downstairs': 'внизу',
        'draw': 'рисовать',
        'dress': 'платье',
        'drink': 'пить',
        'drive': 'водить',
        'driver': 'водитель',
        'during': 'во время',
        'dvd': 'диск',
        'each': 'каждый',
        'ear': 'ухо',
        'early': 'рано',
        'east': 'восток',
        'easy': 'легкий',
        'eat': 'есть',
        'egg': 'яйцо',
        'eight': 'восемь',
        'eighteen': 'восемнадцать',
        'eighty': 'восемьдесят',
        'elephant': 'слон',
        'eleven': 'одиннадцать',
        'else': 'еще',
        'email': 'электронная почта',
        'end': 'конец',
        'enjoy': 'наслаждаться',
        'enough': 'достаточно',
        'euro': 'евро',
        'even': 'даже',
        'evening': 'вечер',
        'event': 'событие',
        'ever': 'когда-либо',
        'every': 'каждый',
        'everybody': 'все',
        'everyone': 'все',
        'everything': 'все',
        'exam': 'экзамен',
        'example': 'пример',
        'excited': 'взволнованный',
        'exciting': 'захватывающий',
        'exercise': 'упражнение',
        'expensive': 'дорогой',
        'explain': 'объяснять',
        'extra': 'дополнительный',
        'eye': 'глаз',
        'face': 'лицо',
        'fact': 'факт',
        'fall': 'падать',
        'false': 'ложный',
        'family': 'семья',
        'famous': 'знаменитый',
        'fantastic': 'фантастический',
        'far': 'далеко',
        'farm': 'ферма',
        'farmer': 'фермер',
        'fast': 'быстрый',
        'fat': 'толстый',
        'father': 'отец',
        'favourite': 'любимый',
        'february': 'февраль',
        'feel': 'чувствовать',
        'feeling': 'чувство',
        'festival': 'фестиваль',
        'few': 'несколько',
        'fifteen': 'пятнадцать',
        'fifth': 'пятый',
        'fifty': 'пятьдесят',
        'fill': 'заполнять',
        'film': 'фильм',
        'final': 'финальный',
        'find': 'находить',
        'fine': 'хорошо',
        'finish': 'заканчивать',
        'fire': 'огонь',
        'first': 'первый',
        'fish': 'рыба',
        'five': 'пять',
        'flat': 'квартира',
        'flight': 'полет',
        'floor': 'пол',
        'flower': 'цветок',
        'fly': 'летать',
        'follow': 'следовать',
        'food': 'еда',
        'foot': 'нога',
        'football': 'футбол',
        'for': 'для',
        'forget': 'забывать',
        'form': 'форма',
        'forty': 'сорок',
        'four': 'четыре',
        'fourteen': 'четырнадцать',
        'fourth': 'четвертый',
        'free': 'свободный',
        'friday': 'пятница',
        'friend': 'друг',
        'friendly': 'дружелюбный',
        'from': 'из',
        'front': 'перед',
        'fruit': 'фрукт',
        'full': 'полный',
        'fun': 'веселье',
        'funny': 'смешной',
        'future': 'будущее',
        'game': 'игра',
        'garden': 'сад',
        'geography': 'география',
        'get': 'получать',
        'girl': 'девочка',
        'girlfriend': 'девушка',
        'give': 'давать',
        'glass': 'стекло',
        'go': 'идти',
        'good': 'хороший',
        'goodbye': 'до свидания',
        'grandfather': 'дедушка',
        'grandmother': 'бабушка',
        'grandparent': 'дедушка/бабушка',
        'great': 'великий',
        'green': 'зеленый',
        'grey': 'серый',
        'group': 'группа',
        'grow': 'расти',
        'guess': 'угадывать',
        'guitar': 'гитара',
        'gym': 'спортзал',
        'hair': 'волосы',
        'half': 'половина',
        'hand': 'рука',
        'happen': 'происходить',
        'happy': 'счастливый',
        'hard': 'трудный',
        'hat': 'шляпа',
        'hate': 'ненавидеть',
        'have': 'иметь',
        'he': 'он',
        'head': 'голова',
        'health': 'здоровье',
        'healthy': 'здоровый',
        'hear': 'слышать',
        'hello': 'привет',
        'help': 'помогать',
        'her': 'ее',
        'here': 'здесь',
        'hey': 'эй',
        'hi': 'привет',
        'high': 'высокий',
        'him': 'его',
        'his': 'его',
        'history': 'история',
        'hobby': 'хобби',
        'holiday': 'праздник',
        'home': 'дом',
        'homework': 'домашнее задание',
        'hope': 'надеяться',
        'horse': 'лошадь',
        'hospital': 'больница',
        'hot': 'горячий',
        'hotel': 'отель',
        'hour': 'час',
        'house': 'дом',
        'how': 'как',
        'however': 'однако',
        'hundred': 'сто',
        'hungry': 'голодный',
        'husband': 'муж',
        'i': 'я',
        'ice': 'лед',
        'idea': 'идея',
        'if': 'если',
        'imagine': 'представлять',
        'important': 'важный',
        'improve': 'улучшать',
        'in': 'в',
        'include': 'включать',
        'information': 'информация',
        'interest': 'интерес',
        'interested': 'заинтересованный',
        'interesting': 'интересный',
        'internet': 'интернет',
        'interview': 'интервью',
        'into': 'в',
        'introduce': 'представлять',
        'island': 'остров',
        'it': 'это',
        'its': 'его',
        'jacket': 'куртка',
        'january': 'январь',
        'jeans': 'джинсы',
        'job': 'работа',
        'join': 'присоединяться',
        'journey': 'путешествие',
        'juice': 'сок',
        'july': 'июль',
        'june': 'июнь',
        'just': 'просто',
        'keep': 'держать',
        'key': 'ключ',
        'kilometre': 'километр',
        'kind': 'добрый',
        'kitchen': 'кухня',
        'know': 'знать',
        'land': 'земля',
        'language': 'язык',
        'large': 'большой',
        'last': 'последний',
        'late': 'поздний',
        'later': 'позже',
        'laugh': 'смеяться',
        'learn': 'учиться',
        'leave': 'покидать',
        'left': 'левый',
        'leg': 'нога',
        'lesson': 'урок',
        'let': 'позволять',
        'letter': 'письмо',
        'library': 'библиотека',
        'lie': 'лежать',
        'life': 'жизнь',
        'light': 'свет',
        'like': 'нравиться',
        'line': 'линия',
        'lion': 'лев',
        'list': 'список',
        'listen': 'слушать',
        'little': 'маленький',
        'live': 'жить',
        'local': 'местный',
        'long': 'длинный',
        'look': 'смотреть',
        'lose': 'терять',
        'lot': 'много',
        'love': 'любить',
        'lunch': 'обед',
        'machine': 'машина',
        'magazine': 'журнал',
        'main': 'главный',
        'make': 'делать',
        'man': 'мужчина',
        'many': 'много',
        'map': 'карта',
        'march': 'март',
        'market': 'рынок',
        'married': 'женатый',
        'match': 'матч',
        'may': 'май',
        'maybe': 'может быть',
        'me': 'мне',
        'meal': 'еда',
        'mean': 'означать',
        'meaning': 'значение',
        'meat': 'мясо',
        'meet': 'встречать',
        'meeting': 'встреча',
        'member': 'член',
        'menu': 'меню',
        'message': 'сообщение',
        'metre': 'метр',
        'midnight': 'полночь',
        'mile': 'миля',
        'milk': 'молоко',
        'million': 'миллион',
        'minute': 'минута',
        'miss': 'скучать',
        'mistake': 'ошибка',
        'model': 'модель',
        'modern': 'современный',
        'moment': 'момент',
        'monday': 'понедельник',
        'money': 'деньги',
        'month': 'месяц',
        'more': 'больше',
        'morning': 'утро',
        'most': 'большинство',
        'mother': 'мать',
        'mountain': 'гора',
        'mouse': 'мышь',
        'mouth': 'рот',
        'move': 'двигаться',
        'movie': 'фильм',
        'much': 'много',
        'mum': 'мама',
        'museum': 'музей',
        'music': 'музыка',
        'must': 'должен',
        'my': 'мой',
        'name': 'имя',
        'natural': 'естественный',
        'near': 'рядом',
        'need': 'нуждаться',
        'negative': 'отрицательный',
        'neighbour': 'сосед',
        'never': 'никогда',
        'new': 'новый',
        'news': 'новости',
        'newspaper': 'газета',
        'next': 'следующий',
        'nice': 'хороший',
        'night': 'ночь',
        'nine': 'девять',
        'nineteen': 'девятнадцать',
        'ninety': 'девяносто',
        'no': 'нет',
        'nobody': 'никто',
        'north': 'север',
        'nose': 'нос',
        'not': 'не',
        'note': 'заметка',
        'nothing': 'ничего',
        'november': 'ноябрь',
        'now': 'сейчас',
        'number': 'число',
        'nurse': 'медсестра',
        'object': 'объект',
        'october': 'октябрь',
        'of': 'из',
        'off': 'выключенный',
        'office': 'офис',
        'often': 'часто',
        'oh': 'о',
        'ok': 'хорошо',
        'old': 'старый',
        'on': 'на',
        'once': 'однажды',
        'one': 'один',
        'onion': 'лук',
        'online': 'онлайн',
        'only': 'только',
        'open': 'открывать',
        'opinion': 'мнение',
        'opposite': 'противоположный',
        'or': 'или',
        'orange': 'оранжевый',
        'order': 'заказ',
        'other': 'другой',
        'our': 'наш',
        'out': 'из',
        'outside': 'снаружи',
        'over': 'над',
        'own': 'собственный',
        'page': 'страница',
        'paint': 'красить',
        'painting': 'картина',
        'pair': 'пара',
        'paper': 'бумага',
        'paragraph': 'параграф',
        'parent': 'родитель',
        'park': 'парк',
        'part': 'часть',
        'partner': 'партнер',
        'party': 'вечеринка',
        'passport': 'паспорт',
        'past': 'прошлое',
        'pay': 'платить',
        'pen': 'ручка',
        'pencil': 'карандаш',
        'people': 'люди',
        'pepper': 'перец',
        'perfect': 'идеальный',
        'period': 'период',
        'person': 'человек',
        'personal': 'личный',
        'phone': 'телефон',
        'photo': 'фото',
        'photograph': 'фотография',
        'phrase': 'фраза',
        'piano': 'пианино',
        'picture': 'картинка',
        'piece': 'кусок',
        'pig': 'свинья',
        'pink': 'розовый',
        'place': 'место',
        'plan': 'план',
        'plane': 'самолет',
        'plant': 'растение',
        'play': 'играть',
        'player': 'игрок',
        'please': 'пожалуйста',
        'point': 'точка',
        'police': 'полиция',
        'policeman': 'полицейский',
        'pool': 'бассейн',
        'poor': 'бедный',
        'popular': 'популярный',
        'positive': 'положительный',
        'possible': 'возможный',
        'post': 'почта',
        'potato': 'картофель',
        'pound': 'фунт',
        'practice': 'практика',
        'practise': 'практиковать',
        'prefer': 'предпочитать',
        'prepare': 'готовить',
        'present': 'подарок',
        'pretty': 'красивый',
        'price': 'цена',
        'probably': 'вероятно',
        'problem': 'проблема',
        'product': 'продукт',
        'programme': 'программа',
        'project': 'проект',
        'purple': 'фиолетовый',
        'put': 'класть',
        'quarter': 'четверть',
        'question': 'вопрос',
        'quick': 'быстрый',
        'quickly': 'быстро',
        'quiet': 'тихий',
        'quite': 'довольно',
        'radio': 'радио',
        'rain': 'дождь',
        'read': 'читать',
        'reader': 'читатель',
        'reading': 'чтение',
        'ready': 'готовый',
        'real': 'настоящий',
        'really': 'действительно',
        'reason': 'причина',
        'red': 'красный',
        'relax': 'расслабляться',
        'remember': 'помнить',
        'repeat': 'повторять',
        'report': 'отчет',
        'restaurant': 'ресторан',
        'result': 'результат',
        'return': 'возвращаться',
        'rice': 'рис',
        'rich': 'богатый',
        'ride': 'ездить',
        'right': 'правый',
        'river': 'река',
        'road': 'дорога',
        'room': 'комната',
        'routine': 'рутина',
        'rule': 'правило',
        'run': 'бегать',
        'sad': 'грустный',
        'salad': 'салат',
        'salt': 'соль',
        'same': 'тот же',
        'sandwich': 'бутерброд',
        'saturday': 'суббота',
        'say': 'говорить',
        'school': 'школа',
        'science': 'наука',
        'scientist': 'ученый',
        'sea': 'море',
        'second': 'второй',
        'section': 'секция',
        'see': 'видеть',
        'sell': 'продавать',
        'send': 'отправлять',
        'sentence': 'предложение',
        'september': 'сентябрь',
        'seven': 'семь',
        'seventeen': 'семнадцать',
        'seventy': 'семьдесят',
        'share': 'делиться',
        'she': 'она',
        'sheep': 'овца',
        'shirt': 'рубашка',
        'shoe': 'обувь',
        'shop': 'магазин',
        'shopping': 'покупки',
        'short': 'короткий',
        'should': 'следует',
        'show': 'показывать',
        'shower': 'душ',
        'sick': 'больной',
        'similar': 'похожий',
        'sing': 'петь',
        'singer': 'певец',
        'sister': 'сестра',
        'sit': 'сидеть',
        'situation': 'ситуация',
        'six': 'шесть',
        'sixteen': 'шестнадцать',
        'sixty': 'шестьдесят',
        'skill': 'навык',
        'skirt': 'юбка',
        'sleep': 'спать',
        'slow': 'медленный',
        'small': 'маленький',
        'snake': 'змея',
        'snow': 'снег',
        'so': 'так',
        'some': 'некоторый',
        'somebody': 'кто-то',
        'someone': 'кто-то',
        'something': 'что-то',
        'sometimes': 'иногда',
        'son': 'сын',
        'song': 'песня',
        'soon': 'скоро',
        'sorry': 'извините',
        'sound': 'звук',
        'soup': 'суп',
        'south': 'юг',
        'space': 'пространство',
        'speak': 'говорить',
        'special': 'особенный',
        'spell': 'произносить по буквам',
        'spelling': 'правописание',
        'spend': 'тратить',
        'sport': 'спорт',
        'spring': 'весна',
        'stand': 'стоять',
        'star': 'звезда',
        'start': 'начинать',
        'statement': 'утверждение',
        'station': 'станция',
        'stay': 'оставаться',
        'still': 'все еще',
        'stop': 'останавливаться',
        'story': 'история',
        'street': 'улица',
        'strong': 'сильный',
        'student': 'студент',
        'study': 'изучать',
        'style': 'стиль',
        'subject': 'предмет',
        'success': 'успех',
        'sugar': 'сахар',
        'summer': 'лето',
        'sun': 'солнце',
        'sunday': 'воскресенье',
        'supermarket': 'супермаркет',
        'sure': 'уверенный',
        'sweater': 'свитер',
        'swim': 'плавать',
        'swimming': 'плавание',
        'table': 'стол',
        'take': 'брать',
        'talk': 'говорить',
        'tall': 'высокий',
        'taxi': 'такси',
        'tea': 'чай',
        'teach': 'учить',
        'teacher': 'учитель',
        'team': 'команда',
        'teenager': 'подросток',
        'telephone': 'телефон',
        'television': 'телевидение',
        'tell': 'рассказывать',
        'ten': 'десять',
        'tennis': 'теннис',
        'terrible': 'ужасный',
        'test': 'тест',
        'text': 'текст',
        'than': 'чем',
        'thank': 'благодарить',
        'thanks': 'спасибо',
        'that': 'тот',
        'the': 'определенный артикль',
        'theatre': 'театр',
        'their': 'их',
        'them': 'их',
        'then': 'тогда',
        'there': 'там',
        'they': 'они',
        'thing': 'вещь',
        'think': 'думать',
        'third': 'третий',
        'thirsty': 'жаждущий',
        'thirteen': 'тринадцать',
        'thirty': 'тридцать',
        'this': 'этот',
        'thousand': 'тысяча',
        'three': 'три',
        'through': 'через',
        'thursday': 'четверг',
        'ticket': 'билет',
        'time': 'время',
        'tired': 'уставший',
        'title': 'заголовок',
        'to': 'к',
        'today': 'сегодня',
        'together': 'вместе',
        'toilet': 'туалет',
        'tomato': 'помидор',
        'tomorrow': 'завтра',
        'tonight': 'сегодня вечером',
        'too': 'тоже',
        'tooth': 'зуб',
        'topic': 'тема',
        'tourist': 'турист',
        'town': 'город',
        'traffic': 'движение',
        'train': 'поезд',
        'travel': 'путешествовать',
        'tree': 'дерево',
        'trip': 'поездка',
        'trousers': 'брюки',
        'true': 'правда',
        'try': 'пытаться',
        'tuesday': 'вторник',
        'turn': 'поворачивать',
        'tv': 'телевизор',
        'twelve': 'двенадцать',
        'twenty': 'двадцать',
        'twice': 'дважды',
        'two': 'два',
        'type': 'тип',
        'umbrella': 'зонт',
        'uncle': 'дядя',
        'under': 'под',
        'understand': 'понимать',
        'university': 'университет',
        'until': 'до',
        'up': 'вверх',
        'upstairs': 'наверху',
        'us': 'нас',
        'use': 'использовать',
        'useful': 'полезный',
        'usually': 'обычно',
        'vacation': 'отпуск',
        'vegetable': 'овощ',
        'very': 'очень',
        'video': 'видео',
        'village': 'деревня',
        'visit': 'посещать',
        'visitor': 'посетитель',
        'wait': 'ждать',
        'waiter': 'официант',
        'wake': 'просыпаться',
        'walk': 'ходить',
        'wall': 'стена',
        'want': 'хотеть',
        'warm': 'теплый',
        'wash': 'мыть',
        'watch': 'смотреть',
        'water': 'вода',
        'way': 'путь',
        'we': 'мы',
        'wear': 'носить',
        'weather': 'погода',
        'website': 'веб-сайт',
        'wednesday': 'среда',
        'week': 'неделя',
        'weekend': 'выходные',
        'welcome': 'добро пожаловать',
        'well': 'хорошо',
        'west': 'запад',
        'what': 'что',
        'when': 'когда',
        'where': 'где',
        'which': 'который',
        'white': 'белый',
        'who': 'кто',
        'why': 'почему',
        'wife': 'жена',
        'will': 'будет',
        'win': 'выигрывать',
        'window': 'окно',
        'wine': 'вино',
        'winter': 'зима',
        'with': 'с',
        'without': 'без',
        'woman': 'женщина',
        'wonderful': 'замечательный',
        'word': 'слово',
        'work': 'работать',
        'worker': 'рабочий',
        'world': 'мир',
        'would': 'бы',
        'write': 'писать',
        'writer': 'писатель',
        'writing': 'письмо',
        'wrong': 'неправильный',
        'yeah': 'да',
        'year': 'год',
        'yellow': 'желтый',
        'yes': 'да',
        'yesterday': 'вчера',
        'you': 'ты',
        'young': 'молодой',
        'your': 'твой',
        'yourself': 'себя'
    }
    
    # Split content by levels
    sections = re.split(r'\b(A1|A2|B1|B2)\b', content)
    
    current_level = None
    for section in sections:
        section = section.strip()
        if section in ['A1', 'A2', 'B1', 'B2']:
            current_level = section
        elif current_level and section:
            # Extract words from section
            words = extract_words_from_section(section, current_level, basic_translations)
            words_by_level[current_level].extend(words)
    
    return words_by_level

def extract_words_from_section(text, level, translations):
    """Extract words from a text section"""
    words = []
    
    # Remove page headers and footers
    text = re.sub(r'© Oxford University Press.*?\d+\s*/\s*\d+', '', text, flags=re.DOTALL)
    text = re.sub(r'The Oxford 3000™ by CEFR level', '', text)
    text = re.sub(r'--- PAGE \d+ ---', '', text)
    
    # Split by lines and process each line
    lines = text.split('\n')
    
    for line in lines:
        line = line.strip()
        if not line:
            continue
            
        # Extract words with their parts of speech
        # Pattern: word part_of_speech
        word_matches = re.findall(r'\b([a-zA-Z]+(?:\s+[a-zA-Z]+)*)\s+([a-z]+\.(?:,\s*[a-z]+\.)*)', line)
        
        for word_match in word_matches:
            word = word_match[0].lower().strip()
            pos = word_match[1]
            
            # Skip very short words or common function words
            if len(word) < 2 or word in ['a', 'an', 'the', 'of', 'to', 'and', 'or']:
                continue
                
            # Get translation or use placeholder
            translation = translations.get(word, f'перевод для {word}')
            
            # Determine category based on part of speech
            category = get_category_from_pos(pos)
            
            words.append({
                'word': word,
                'translation': translation,
                'category': category,
                'pos': pos
            })
    
    # Remove duplicates
    seen = set()
    unique_words = []
    for word_data in words:
        if word_data['word'] not in seen:
            seen.add(word_data['word'])
            unique_words.append(word_data)
    
    return unique_words[:50]  # Limit to 50 words per level for demo

def get_category_from_pos(pos):
    """Get category based on part of speech"""
    if 'n.' in pos:
        return 'nouns'
    elif 'v.' in pos:
        return 'verbs'
    elif 'adj.' in pos:
        return 'adjectives'
    elif 'adv.' in pos:
        return 'adverbs'
    elif 'prep.' in pos:
        return 'prepositions'
    elif 'conj.' in pos:
        return 'conjunctions'
    elif 'pron.' in pos:
        return 'pronouns'
    elif 'det.' in pos:
        return 'determiners'
    elif 'modal' in pos:
        return 'modal_verbs'
    elif 'number' in pos:
        return 'numbers'
    elif 'exclam.' in pos:
        return 'exclamations'
    else:
        return 'other'

if __name__ == '__main__':
    print("Parsing Oxford 3000 words...")
    words_data = parse_oxford_words()
    
    # Save to JavaScript file
    js_content = f"""// Oxford 3000 Words Database - Enhanced with real Oxford words
const oxfordWordsDatabase = {json.dumps(words_data, ensure_ascii=False, indent=2)};

// Export for use in application
if (typeof module !== 'undefined' && module.exports) {{
  module.exports = oxfordWordsDatabase;
}}"""
    
    with open('/home/ubuntu/english-words-app/oxford_words_data.js', 'w', encoding='utf-8') as f:
        f.write(js_content)
    
    # Print statistics
    total_words = sum(len(words) for words in words_data.values())
    print(f"Successfully parsed {total_words} words:")
    for level, words in words_data.items():
        print(f"  {level}: {len(words)} words")
    
    print("Oxford words database saved to oxford_words_data.js")

