// База данных слов по уровням английского языка
const wordsDatabase = {
  "A1": [
    { word: "hello", translation: "привет", category: "greetings" },
    { word: "goodbye", translation: "до свидания", category: "greetings" },
    { word: "please", translation: "пожалуйста", category: "politeness" },
    { word: "thank", translation: "благодарить", category: "politeness" },
    { word: "yes", translation: "да", category: "basic" },
    { word: "no", translation: "нет", category: "basic" },
    { word: "water", translation: "вода", category: "food" },
    { word: "food", translation: "еда", category: "food" },
    { word: "house", translation: "дом", category: "places" },
    { word: "family", translation: "семья", category: "people" },
    { word: "friend", translation: "друг", category: "people" },
    { word: "work", translation: "работа", category: "activities" },
    { word: "school", translation: "школа", category: "places" },
    { word: "book", translation: "книга", category: "objects" },
    { word: "car", translation: "машина", category: "transport" },
    { word: "time", translation: "время", category: "abstract" },
    { word: "day", translation: "день", category: "time" },
    { word: "night", translation: "ночь", category: "time" },
    { word: "good", translation: "хороший", category: "adjectives" },
    { word: "bad", translation: "плохой", category: "adjectives" }
  ],
  "A2": [
    { word: "beautiful", translation: "красивый", category: "adjectives" },
    { word: "important", translation: "важный", category: "adjectives" },
    { word: "different", translation: "разный", category: "adjectives" },
    { word: "interesting", translation: "интересный", category: "adjectives" },
    { word: "difficult", translation: "трудный", category: "adjectives" },
    { word: "possible", translation: "возможный", category: "adjectives" },
    { word: "necessary", translation: "необходимый", category: "adjectives" },
    { word: "available", translation: "доступный", category: "adjectives" },
    { word: "comfortable", translation: "удобный", category: "adjectives" },
    { word: "expensive", translation: "дорогой", category: "adjectives" },
    { word: "cheap", translation: "дешевый", category: "adjectives" },
    { word: "dangerous", translation: "опасный", category: "adjectives" },
    { word: "safe", translation: "безопасный", category: "adjectives" },
    { word: "healthy", translation: "здоровый", category: "adjectives" },
    { word: "sick", translation: "больной", category: "adjectives" },
    { word: "happy", translation: "счастливый", category: "emotions" },
    { word: "sad", translation: "грустный", category: "emotions" },
    { word: "angry", translation: "злой", category: "emotions" },
    { word: "tired", translation: "уставший", category: "emotions" },
    { word: "excited", translation: "взволнованный", category: "emotions" }
  ],
  "B1": [
    { word: "achievement", translation: "достижение", category: "abstract" },
    { word: "advantage", translation: "преимущество", category: "abstract" },
    { word: "adventure", translation: "приключение", category: "abstract" },
    { word: "agreement", translation: "соглашение", category: "abstract" },
    { word: "appearance", translation: "внешность", category: "abstract" },
    { word: "appointment", translation: "назначение", category: "abstract" },
    { word: "approach", translation: "подход", category: "abstract" },
    { word: "argument", translation: "аргумент", category: "abstract" },
    { word: "arrangement", translation: "договоренность", category: "abstract" },
    { word: "atmosphere", translation: "атмосфера", category: "abstract" },
    { word: "attitude", translation: "отношение", category: "abstract" },
    { word: "audience", translation: "аудитория", category: "people" },
    { word: "background", translation: "фон, происхождение", category: "abstract" },
    { word: "balance", translation: "баланс", category: "abstract" },
    { word: "behavior", translation: "поведение", category: "abstract" },
    { word: "benefit", translation: "польза", category: "abstract" },
    { word: "budget", translation: "бюджет", category: "money" },
    { word: "challenge", translation: "вызов", category: "abstract" },
    { word: "character", translation: "характер", category: "abstract" },
    { word: "choice", translation: "выбор", category: "abstract" }
  ],
  "B2": [
    { word: "accomplish", translation: "выполнять", category: "verbs" },
    { word: "acknowledge", translation: "признавать", category: "verbs" },
    { word: "acquire", translation: "приобретать", category: "verbs" },
    { word: "adapt", translation: "адаптироваться", category: "verbs" },
    { word: "adequate", translation: "адекватный", category: "adjectives" },
    { word: "advocate", translation: "защищать", category: "verbs" },
    { word: "alternative", translation: "альтернатива", category: "abstract" },
    { word: "analyze", translation: "анализировать", category: "verbs" },
    { word: "anticipate", translation: "предвидеть", category: "verbs" },
    { word: "apparent", translation: "очевидный", category: "adjectives" },
    { word: "appreciate", translation: "ценить", category: "verbs" },
    { word: "appropriate", translation: "подходящий", category: "adjectives" },
    { word: "approximate", translation: "приблизительный", category: "adjectives" },
    { word: "arbitrary", translation: "произвольный", category: "adjectives" },
    { word: "aspect", translation: "аспект", category: "abstract" },
    { word: "assess", translation: "оценивать", category: "verbs" },
    { word: "assume", translation: "предполагать", category: "verbs" },
    { word: "assure", translation: "уверять", category: "verbs" },
    { word: "attach", translation: "прикреплять", category: "verbs" },
    { word: "attribute", translation: "приписывать", category: "verbs" }
  ],
  "C1": [
    { word: "abstract", translation: "абстрактный", category: "adjectives" },
    { word: "abundant", translation: "изобильный", category: "adjectives" },
    { word: "accelerate", translation: "ускорять", category: "verbs" },
    { word: "accommodate", translation: "размещать", category: "verbs" },
    { word: "accumulate", translation: "накапливать", category: "verbs" },
    { word: "accurate", translation: "точный", category: "adjectives" },
    { word: "adjacent", translation: "смежный", category: "adjectives" },
    { word: "advocate", translation: "сторонник", category: "nouns" },
    { word: "aesthetic", translation: "эстетический", category: "adjectives" },
    { word: "aggregate", translation: "совокупность", category: "nouns" },
    { word: "allocate", translation: "распределять", category: "verbs" },
    { word: "ambiguous", translation: "двусмысленный", category: "adjectives" },
    { word: "analogous", translation: "аналогичный", category: "adjectives" },
    { word: "anticipate", translation: "предвосхищать", category: "verbs" },
    { word: "arbitrary", translation: "произвольный", category: "adjectives" },
    { word: "articulate", translation: "четко выражать", category: "verbs" },
    { word: "assimilate", translation: "усваивать", category: "verbs" },
    { word: "attribute", translation: "свойство", category: "nouns" },
    { word: "autonomous", translation: "автономный", category: "adjectives" },
    { word: "coherent", translation: "связный", category: "adjectives" }
  ],
  "C2": [
    { word: "aberration", translation: "отклонение", category: "nouns" },
    { word: "abstruse", translation: "непонятный", category: "adjectives" },
    { word: "accentuate", translation: "подчеркивать", category: "verbs" },
    { word: "acquiesce", translation: "молчаливо соглашаться", category: "verbs" },
    { word: "admonish", translation: "предостерегать", category: "verbs" },
    { word: "aesthetic", translation: "эстетика", category: "nouns" },
    { word: "alleviate", translation: "облегчать", category: "verbs" },
    { word: "amalgamate", translation: "объединять", category: "verbs" },
    { word: "ambivalent", translation: "двойственный", category: "adjectives" },
    { word: "ameliorate", translation: "улучшать", category: "verbs" },
    { word: "anachronism", translation: "анахронизм", category: "nouns" },
    { word: "analogous", translation: "аналогичный", category: "adjectives" },
    { word: "anecdotal", translation: "основанный на слухах", category: "adjectives" },
    { word: "anomaly", translation: "аномалия", category: "nouns" },
    { word: "antipathy", translation: "антипатия", category: "nouns" },
    { word: "apathy", translation: "апатия", category: "nouns" },
    { word: "apprehensive", translation: "опасающийся", category: "adjectives" },
    { word: "arbitrary", translation: "произвольный", category: "adjectives" },
    { word: "archaic", translation: "архаичный", category: "adjectives" },
    { word: "articulate", translation: "красноречивый", category: "adjectives" }
  ]
};

// Экспорт для использования в приложении
if (typeof module !== 'undefined' && module.exports) {
  module.exports = wordsDatabase;
}

